This pull request adds support for Swift Package Manager
superpeteblaze/ScalingCarousel pull request #82
Opened 2020-10-01 19:45 UTC by DominatorVbN

# Summary
Fixes #80 
 
- Added support for SPM
- Added installation instruction for SPM
- Added build script in CI pipeline
- Bumped cocoapod version and SPM version to 3.1.1

2020-10-02 06:23 UTC, superpeteblaze requested changes
This is great @DominatorVbN, it all mostly looks good to me. Just one request:

- Can we bump the version to `3.2.0`. As this is a version which adds functionality in a backward-compatible manner, I think this would be more suitable according to semantic versioning. More info on this [here](https://semver.org).

2020-10-02 08:48 UTC, DominatorVbN commented
Hey @superpeteblaze,
I have bumped the version and created the tags,

Mistakenly I wrote wrong commit message, so this forced push,
But it's all good now.

2020-10-04 10:30 UTC, superpeteblaze approved these changes

2020-10-04 10:31 UTC, merged

2020-10-04 10:47 UTC, superpeteblaze commented
I merged and fixed some minor references. Tagged and released! 🚀 Thanks again for the contribution @DominatorVbN 🙌🏽